<?php
/** op-unit-bitcoin:/testcase/getreceivedbyaddress.phtml
 *
 * @created   2021-01-09
 * @package   op-unit-bitcoin
 * @version   1.0
 * @author    Tomoaki Nagahara <tomoaki.nagahara@gmail.com>
 * @copyright Tomoaki Nagahara All right reserved.
 */

/** namespace
 *
 */
namespace OP\UNIT\BITCOIN;

/** use
 *
 */
use function OP\Request;

//	...
$address = Request('address');

?>
<form>
	<table>
		<tr>
			<th>
				address
			</th><td>:</td>
			<td>
				<input type="text" name="address" value="<?= $address ?>" />
			</td>
		</tr><tr>
			<th>

			</th><td></td>
			<td>
				<button> Submit </button>
			</td>
		</tr>
	</table>
</form>
